// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const page: string;
export const markdownBody: string;
export const tableOfContents: string;
export const anchor: string;
export const taskListItem: string;
